-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Decompiled with Medal's Decompiler. (Modified by SignalHub)
-- Decompiled at: 11/8/2025, 4:21:00 PM
-- Cached decompilation

local v1 = require(game.ReplicatedStorage.Shared.SPDict)
local v_u_2 = {
    ["SurfaceAppearanceDecals"] = {},
    ["Priority1"] = v1:new():add_set_from_table_list((f_convert_table_list_gameasset_to_assetid(v11))),
    ["Priority2"] = v1:new():add_set_from_table_list((f_convert_table_list_gameasset_to_assetid(v12)))
}
local v_u_3 = v1:new({
    ["rbxgameasset://Images/WORLD_SIGN_Compete (1)"] = "rbxassetid://837078755",
    ["rbxgameasset://Images/WORLD_Overpass_Rail (1)"] = "rbxassetid://698575332",
    ["rbxgameasset://Images/DanceShop_Arcade-Poster-Main"] = "rbxassetid://3193013880",
    ["rbxgameasset://Images/WORLD_SIGN_COMPETE"] = "rbxassetid://711576203",
    ["rbxgameasset://Images/WORLD_COMPETE_circlelines"] = "rbxassetid://1015152579",
    ["rbxgameasset://Images/WORLD_line2"] = "rbxassetid://717224882",
    ["rbxgameasset://Images/WORLD_BG_fence"] = "rbxassetid://701093389",
    ["rbxgameasset://Images/WORLD_STREET_LINE"] = "rbxassetid://709563650",
    ["rbxgameasset://Images/WORLD_SIDEWALK"] = "rbxassetid://1015192226",
    ["rbxgameasset://Images/WORLD_SQUARE_WHITE"] = "rbxassetid://718811824",
    ["rbxgameasset://Images/WORLD_BG_fence_door"] = "rbxassetid://701093384",
    ["rbxgameasset://Images/WORLD_SIGN_shop_Musicshop"] = "rbxassetid://837093043",
    ["rbxgameasset://Images/WORLD_Overpass_Rail"] = "rbxassetid://698575334",
    ["rbxgameasset://Images/TCUI_coin"] = "rbxassetid://818988511",
    ["rbxgameasset://Images/WORLD_line"] = "rbxassetid://708274234",
    ["rbxgameasset://Images/TCUI_star"] = "rbxassetid://818988515",
    ["rbxgameasset://Images/WORLD_TRUCK_LIGHT_Black"] = "rbxassetid://709320123",
    ["rbxgameasset://Images/Gearshop_outsidesigns_1"] = "rbxassetid://1015167759",
    ["rbxgameasset://Images/Gearshop_outsidesigns_2"] = "rbxassetid://1015167761",
    ["rbxgameasset://Images/WORLD_SIGN_SHOP"] = "rbxassetid://711578653",
    ["rbxgameasset://Images/WORLD_Sign_Robuxbanner"] = "rbxassetid://1203156004",
    ["rbxgameasset://Images/UIM_TeamBillboard"] = "rbxassetid://7000623132",
    ["rbxgameasset://Images/SHOP_poster_2"] = "rbxassetid://924626960",
    ["rbxgameasset://Images/SHOP_poster_1"] = "rbxassetid://886220865",
    ["rbxgameasset://Images/SHOP_poster_3"] = "rbxassetid://886220855",
    ["rbxgameasset://Images/SHOP_poster_4"] = "rbxassetid://886220853",
    ["rbxgameasset://Images/DanceShop_DDRSign"] = "rbxassetid://3193014394",
    ["rbxgameasset://Images/DanceShop_DDRPoster"] = "rbxassetid://3193014339",
    ["rbxgameasset://Images/WORLD_Sign_GachaBG1"] = "rbxassetid://822806230",
    ["rbxgameasset://Images/WORLD_Sign_GachaBG2"] = "rbxassetid://822806227",
    ["rbxgameasset://Images/WORLD_Sign_GachaBG3"] = "rbxassetid://822806228",
    ["rbxgameasset://Images/WORLD_TRUCK_LIGHT2"] = "rbxassetid://709373933",
    ["rbxgameasset://Images/Gearshop_Wall3_6"] = "rbxassetid://1483649761",
    ["rbxgameasset://Images/Gearshop_Wall3_2"] = "rbxassetid://1483649017",
    ["rbxgameasset://Images/Gearshop_Wall3_5"] = "rbxassetid://1483649775",
    ["rbxgameasset://Images/Gearshop_MachineSign_4"] = "rbxassetid://1483644103",
    ["rbxgameasset://Images/Gearshop_MachineSign_3"] = "rbxassetid://1483644105",
    ["rbxgameasset://Images/Gearshop_Wall3_4"] = "rbxassetid://1483649031",
    ["rbxgameasset://Images/Gearshop_MachineSign_2"] = "rbxassetid://1483644096",
    ["rbxgameasset://Images/Gearshop_MachineSign_1"] = "rbxassetid://1483644104",
    ["rbxgameasset://Images/Gearshop_Wall3_1"] = "rbxassetid://1483649012",
    ["rbxgameasset://Images/Gearshop_Wall3_8"] = "rbxassetid://1483649787",
    ["rbxgameasset://Images/Gearshop_Wall3_3"] = "rbxassetid://1483649025",
    ["rbxgameasset://Images/Gearshop_Wall3_7"] = "rbxassetid://1483649781",
    ["rbxgameasset://Images/Marketplace_VerticalBanner6"] = "rbxassetid://4675592844",
    ["rbxgameasset://Images/Marketplace_VerticalBanner3"] = "rbxassetid://4675592987",
    ["rbxgameasset://Images/Marketplace_VerticalBanner4"] = "rbxassetid://4675593088",
    ["rbxgameasset://Images/Marketplace_VerticalBanner5"] = "rbxassetid://4675593124",
    ["rbxgameasset://Images/Marketplace_VerticalBanner2"] = "rbxassetid://4675592948",
    ["rbxgameasset://Images/Marketplace_VerticalBanner1"] = "rbxassetid://4675592904",
    ["rbxgameasset://Images/Marketplace_HorizontalBanner2"] = "rbxassetid://4675593040",
    ["rbxgameasset://Images/Marketplace_HorizontalBanner1"] = "rbxassetid://4675592647",
    ["rbxgameasset://Images/WClub_DJ-Set"] = "rbxassetid://3125193194",
    ["rbxgameasset://Images/Gearshop_Billboard_1"] = "rbxassetid://1015167757",
    ["rbxgameasset://Images/Gearshop_Billboard_2"] = "rbxassetid://1015167758",
    ["rbxgameasset://Images/Gearshop_Billboard_3"] = "rbxassetid://1015189299",
    ["rbxgameasset://Images/Gearshop_Billboard_4"] = "rbxassetid://1015119006",
    ["rbxgameasset://Images/SHOP_banner_robuxshop"] = "rbxassetid://886220851",
    ["rbxgameasset://Images/WORLD_SIGN_compete_door_side1"] = "rbxassetid://837093034",
    ["rbxgameasset://Images/WORLD_SIGN_shop_sales"] = "rbxassetid://837093049",
    ["rbxgameasset://Images/SHOP_banner_starmachine"] = "rbxassetid://886220854",
    ["rbxgameasset://Images/WORLD_SIGN_Glico"] = "rbxassetid://1015119013",
    ["rbxgameasset://Images/WORLD_SIGN_compete_door_side2"] = "rbxassetid://837093028",
    ["rbxgameasset://Images/WORLD_BG_building1"] = "rbxassetid://924617468",
    ["rbxgameasset://Images/WORLD_BG_building4"] = "rbxassetid://924617484",
    ["rbxgameasset://Images/WORLD_BG_building6"] = "rbxassetid://701009460",
    ["rbxgameasset://Images/WORLD_BG_building2"] = "rbxassetid://924617492",
    ["rbxgameasset://Images/WORLD_BG_building5"] = "rbxassetid://924617516",
    ["rbxgameasset://Images/WORLD_BG_building5b"] = "rbxassetid://699327658",
    ["rbxgameasset://Images/WORLD_BG_building3"] = "rbxassetid://924617490",
    ["rbxgameasset://Images/TCSIGN_square_4"] = "rbxassetid://1015189298",
    ["rbxgameasset://Images/Gearshop_Logo"] = "rbxassetid://1015167760",
    ["rbxgameasset://Images/DanceShop_Arcade-Poster-1"] = "rbxassetid://3193013706",
    ["rbxgameasset://Images/DanceShop_Arcade-Poster-2"] = "rbxassetid://3193013798",
    ["rbxgameasset://Images/DanceShop_DDRFloorTexture"] = "rbxassetid://3193014283",
    ["rbxgameasset://Images/DanceShop_FloorTexture"] = "rbxassetid://3193014470",
    ["rbxgameasset://Images/Gearshop_Rug_Final"] = "rbxassetid://1499764044",
    ["rbxgameasset://Images/Marketplace_Screen1"] = "rbxassetid://4681678462",
    ["rbxgameasset://Images/Marketplace_Screen2"] = "rbxassetid://4681678543",
    ["rbxgameasset://Images/Marketplace_Screen3"] = "rbxassetid://4681678523",
    ["rbxgameasset://Images/Marketplace_Screen4"] = "rbxassetid://4681678491",
    ["rbxgameasset://Images/Robeats-Leaderboard-Textures-Floor-1"] = "rbxassetid://2038180005",
    ["rbxgameasset://Images/Robeats-Leaderboard-Textures-FloorMat-1"] = "rbxassetid://2038182218",
    ["rbxgameasset://Images/Robeats-Leaderboard-Textures-FloorMatCenter-1"] = "rbxassetid://2038186198",
    ["rbxgameasset://Images/TCSIGN_banner_1"] = "rbxassetid://836149897",
    ["rbxgameasset://Images/TCSIGN_banner_2"] = "rbxassetid://836149891",
    ["rbxgameasset://Images/TCSIGN_banner_3"] = "rbxassetid://836149871",
    ["rbxgameasset://Images/TCSIGN_banner_5"] = "rbxassetid://836149859",
    ["rbxgameasset://Images/TCSIGN_banner_6"] = "rbxassetid://858614359",
    ["rbxgameasset://Images/TCSIGN_banner_7"] = "rbxassetid://858614360",
    ["rbxgameasset://Images/TCSIGN_banner_8"] = "rbxassetid://858614360",
    ["rbxgameasset://Images/TCSIGN_horiz_1"] = "rbxassetid://858614375",
    ["rbxgameasset://Images/TCSIGN_horiz_2"] = "rbxassetid://858614377",
    ["rbxgameasset://Images/TCSIGN_longvertical_2"] = "rbxassetid://858614379",
    ["rbxgameasset://Images/TCSIGN_square_2"] = "rbxassetid://836149863",
    ["rbxgameasset://Images/TCSIGN_square_3"] = "rbxassetid://836149872",
    ["rbxgameasset://Images/TCSIGN_square_5"] = "rbxassetid://836149880",
    ["rbxgameasset://Images/TCSIGN_square_6"] = "rbxassetid://836149870",
    ["rbxgameasset://Images/TCSIGN_square_7"] = "rbxassetid://836149853",
    ["rbxgameasset://Images/TCSIGN_subway_poster_4"] = "rbxassetid://836149878",
    ["rbxgameasset://Images/TCSIGN_vertical_3"] = "rbxassetid://858614354",
    ["rbxgameasset://Images/TCSIGN_vertical_6"] = "rbxassetid://858614356",
    ["rbxgameasset://Images/WClub_BigWalls-2"] = "rbxassetid://3125193292",
    ["rbxgameasset://Images/WClub_DJSet-Front-2"] = "rbxassetid://3125193231",
    ["rbxgameasset://Images/WClub_DJSet-Side-2"] = "rbxassetid://3125192980",
    ["rbxgameasset://Images/WClub_SideSpeaker-2"] = "rbxassetid://3125193084",
    ["rbxgameasset://Images/WClub_Speaker-1"] = "rbxassetid://3125193018",
    ["rbxgameasset://Images/WClub_SpeakerFront-Front-4"] = "rbxassetid://3125193162",
    ["rbxgameasset://Images/WClub_SpeakerFront-Side-2"] = "rbxassetid://3125193261",
    ["rbxgameasset://Images/WClub_TV-Front-2"] = "rbxassetid://3125193052",
    ["rbxgameasset://Images/WClub_TV-Side-2"] = "rbxassetid://3125192945",
    ["rbxgameasset://Images/WClub_Tunnel-Texture"] = "rbxassetid://3125193124",
    ["rbxgameasset://Images/WORLD_BG_fence_pattern"] = "rbxassetid://701093388",
    ["rbxgameasset://Images/WORLD_SIGN_Salon"] = "rbxassetid://837093035",
    ["rbxgameasset://Images/WORLD_SIGN_shop_sales 2"] = "rbxassetid://837093048",
    ["rbxgameasset://Images/WORLD_TRUCK_SPEAKER"] = "rbxassetid://1015192234",
    ["rbxgameasset://Images/TCSIGN_banner_4"] = "rbxassetid://1015150094",
    ["rbxgameasset://Images/WORLD_TRUCK_LIGHT"] = "rbxassetid://709311557",
    ["rbxgameasset://Images/WORLD_TRUCK_TIRE"] = "rbxassetid://10152555562"
})
local function _(p4, p5) --[[ Name: begins_with ]] --[[ Line: 132 ]]
    return p4:sub(1, #p5) == p5;
end;
v_u_2.convert_gameasset_to_assetid = function(_, p6) --[[ Name: convert_gameasset_to_assetid ]] --[[ Line: 136 ]]
    --[[ Upvalues: (copy 1): v_u_3 ]]
    if p6:sub(1, 10) == "rbxassetid" or p6:sub(1, 4) == "http" then
        return p6;
    elseif v_u_3:contains(p6) then
        return v_u_3:get(p6);
    else
        return nil;
    end;
end;
local function f_convert_table_list_gameasset_to_assetid(p7) --[[ Name: convert_table_list_gameasset_to_assetid ]] --[[ Line: 145 ]]
    --[[ Upvalues: (copy 1): v_u_2 ]]
    local v8 = {}
    for _, v9 in pairs(p7) do
        local v10 = v_u_2:convert_gameasset_to_assetid(v9)
        if v10 == nil then
            warn("convert_table_list_gameasset_to_assetid: could not find assetid for gameasset: " .. tostring(v9))
        else
            v8[#v8 + 1] = v10
        end;
    end;
    return v8;
end;
local v11 = {
    "rbxgameasset://Images/WORLD_SIGN_COMPETE",
    "rbxgameasset://Images/WORLD_SIGN_Compete (1)",
    "rbxgameasset://Images/WORLD_COMPETE_circlelines",
    "rbxgameasset://Images/WORLD_line2",
    "rbxgameasset://Images/WORLD_BG_fence",
    "rbxgameasset://Images/WORLD_STREET_LINE",
    "rbxgameasset://Images/WORLD_SIDEWALK",
    "rbxgameasset://Images/WORLD_SQUARE_WHITE",
    "rbxgameasset://Images/WORLD_Overpass_Rail (1)",
    "rbxgameasset://Images/WORLD_BG_fence_door",
    "rbxgameasset://Images/WORLD_SIGN_shop_Musicshop",
    "rbxgameasset://Images/WORLD_Overpass_Rail",
    "rbxgameasset://Images/TCUI_coin",
    "rbxgameasset://Images/WORLD_line",
    "rbxgameasset://Images/TCUI_star",
    "rbxgameasset://Images/WORLD_TRUCK_LIGHT_Black",
    "rbxgameasset://Images/Gearshop_outsidesigns_1",
    "rbxgameasset://Images/Gearshop_outsidesigns_2",
    "rbxgameasset://Images/WORLD_SIGN_SHOP",
    "rbxgameasset://Images/WORLD_Sign_Robuxbanner",
    "rbxgameasset://Images/UIM_TeamBillboard",
    "rbxgameasset://Images/SHOP_poster_2",
    "rbxgameasset://Images/SHOP_poster_1",
    "rbxgameasset://Images/SHOP_poster_3",
    "rbxgameasset://Images/SHOP_poster_4",
    "rbxgameasset://Images/DanceShop_DDRSign",
    "rbxgameasset://Images/DanceShop_DDRPoster",
    "rbxgameasset://Images/DanceShop_Arcade-Poster-Main",
    "rbxgameasset://Images/WORLD_Sign_GachaBG1",
    "rbxgameasset://Images/WORLD_Sign_GachaBG2",
    "rbxgameasset://Images/WORLD_Sign_GachaBG3",
    "rbxgameasset://Images/WORLD_TRUCK_LIGHT_Black",
    "rbxgameasset://Images/WORLD_TRUCK_LIGHT2",
    "rbxgameasset://Images/Gearshop_Wall3_6",
    "rbxgameasset://Images/Gearshop_Wall3_2",
    "rbxgameasset://Images/Gearshop_Wall3_5",
    "rbxgameasset://Images/Gearshop_MachineSign_4",
    "rbxgameasset://Images/Gearshop_MachineSign_3",
    "rbxgameasset://Images/Gearshop_Wall3_4",
    "rbxgameasset://Images/Gearshop_MachineSign_2",
    "rbxgameasset://Images/Gearshop_MachineSign_1",
    "rbxgameasset://Images/Gearshop_Wall3_1",
    "rbxgameasset://Images/Gearshop_Wall3_8",
    "rbxgameasset://Images/Gearshop_Wall3_3",
    "rbxgameasset://Images/Gearshop_Wall3_7",
    "rbxgameasset://Images/Marketplace_VerticalBanner6",
    "rbxgameasset://Images/Marketplace_VerticalBanner3",
    "rbxgameasset://Images/Marketplace_VerticalBanner4",
    "rbxgameasset://Images/Marketplace_VerticalBanner5",
    "rbxgameasset://Images/Marketplace_VerticalBanner2",
    "rbxgameasset://Images/Marketplace_VerticalBanner1",
    "rbxgameasset://Images/Marketplace_HorizontalBanner2",
    "rbxgameasset://Images/Marketplace_HorizontalBanner1",
    "rbxgameasset://Images/WClub_DJ-Set",
    "rbxassetid://4675622689",
    "http://www.roblox.com/asset/?id=7000132607",
    "http://www.roblox.com/asset/?id=7000084839",
    "http://www.roblox.com/asset/?id=7000085073",
    "rbxassetid://837093029",
    "rbxassetid://837093054",
    "rbxassetid://836149871",
    "rbxgameasset://Images/Gearshop_Billboard_1",
    "rbxgameasset://Images/Gearshop_Billboard_2",
    "rbxgameasset://Images/Gearshop_Billboard_3",
    "rbxgameasset://Images/Gearshop_Billboard_4",
    "rbxgameasset://Images/DanceShop_Arcade-Poster-1",
    "rbxgameasset://Images/DanceShop_Arcade-Poster-2",
    "rbxgameasset://Images/TCSIGN_square_3",
    "rbxgameasset://Images/TCSIGN_square_4",
    "rbxgameasset://Images/TCSIGN_banner_1",
    "rbxgameasset://Images/TCSIGN_banner_2",
    "rbxgameasset://Images/TCSIGN_banner_5",
    "rbxgameasset://Images/TCSIGN_banner_7"
}
local v12 = {
    "rbxgameasset://Images/SHOP_banner_robuxshop",
    "rbxgameasset://Images/WORLD_SIGN_compete_door_side1",
    "rbxgameasset://Images/WORLD_SIGN_shop_sales",
    "rbxgameasset://Images/SHOP_poster_4",
    "rbxgameasset://Images/SHOP_banner_starmachine",
    "rbxgameasset://Images/WORLD_SIGN_Glico",
    "rbxgameasset://Images/WORLD_SIGN_compete_door_side2",
    "rbxgameasset://Images/WORLD_BG_building1",
    "rbxgameasset://Images/WORLD_BG_building4",
    "rbxgameasset://Images/WORLD_BG_building6",
    "rbxgameasset://Images/WORLD_BG_building2",
    "rbxgameasset://Images/WORLD_BG_building5",
    "rbxgameasset://Images/WORLD_BG_building5b",
    "rbxgameasset://Images/WORLD_BG_building3"
}
return v_u_2;
